apiVersion: v1
kind: ReplicationController 
metadata: 
  name: mylogin-rc
spec: 
  replicas: 3
  selector: 
     app: mynginx 
  template:
   metadata: 
     labels:
        app: mynginx  
   spec: 
     containers: 
     - name: mynginx-container
       image: nginx 
       port: 
         - containerPort: 80      